// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['backend']['App']['Close']();
}

export function CreateCategory(arg1) {
  return window['go']['backend']['App']['CreateCategory'](arg1);
}

export function CreateProduct(arg1) {
  return window['go']['backend']['App']['CreateProduct'](arg1);
}

export function CreateProvider(arg1) {
  return window['go']['backend']['App']['CreateProvider'](arg1);
}

export function Database() {
  return window['go']['backend']['App']['Database']();
}

export function DeleteCategoryById(arg1) {
  return window['go']['backend']['App']['DeleteCategoryById'](arg1);
}

export function DeleteProductById(arg1) {
  return window['go']['backend']['App']['DeleteProductById'](arg1);
}

export function DeleteProviderById(arg1) {
  return window['go']['backend']['App']['DeleteProviderById'](arg1);
}

export function GetAllCategories() {
  return window['go']['backend']['App']['GetAllCategories']();
}

export function GetAllProducts() {
  return window['go']['backend']['App']['GetAllProducts']();
}

export function GetAllProviders() {
  return window['go']['backend']['App']['GetAllProviders']();
}

export function GetProductById(arg1) {
  return window['go']['backend']['App']['GetProductById'](arg1);
}

export function UpdateByProvider(arg1, arg2) {
  return window['go']['backend']['App']['UpdateByProvider'](arg1, arg2);
}

export function UpdateCategoryById(arg1, arg2) {
  return window['go']['backend']['App']['UpdateCategoryById'](arg1, arg2);
}

export function UpdateProductById(arg1, arg2) {
  return window['go']['backend']['App']['UpdateProductById'](arg1, arg2);
}

export function UpdateProviderById(arg1, arg2) {
  return window['go']['backend']['App']['UpdateProviderById'](arg1, arg2);
}
