// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close() {
  return window['go']['backend']['App']['Close']();
}

export function CreateProduct(arg1) {
  return window['go']['backend']['App']['CreateProduct'](arg1);
}

export function Database() {
  return window['go']['backend']['App']['Database']();
}

export function DeleteProduct(arg1) {
  return window['go']['backend']['App']['DeleteProduct'](arg1);
}

export function GetAllProducts() {
  return window['go']['backend']['App']['GetAllProducts']();
}

export function GetProductById(arg1) {
  return window['go']['backend']['App']['GetProductById'](arg1);
}

export function GetProviders() {
  return window['go']['backend']['App']['GetProviders']();
}

export function UpdateByProvider(arg1, arg2) {
  return window['go']['backend']['App']['UpdateByProvider'](arg1, arg2);
}

export function UpdateProduct(arg1, arg2) {
  return window['go']['backend']['App']['UpdateProduct'](arg1, arg2);
}
