// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function Close():Promise<void>;

export function CreateProduct(arg1:backend.Product):Promise<void>;

export function Database():Promise<void>;

export function DeleteProduct(arg1:number):Promise<void>;

export function GetAllProducts():Promise<Array<backend.Product>>;

export function GetProductById(arg1:number):Promise<backend.Product>;

export function UpdateProduct(arg1:number,arg2:backend.Product):Promise<void>;
