// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Database() {
  return window['go']['backend']['App']['Database']();
}

export function GetInfo() {
  return window['go']['backend']['App']['GetInfo']();
}
